#!/bin/bash

source ~/.dotfiles/shell_setup/generic_shell_config


# zsh specific aliases
#-------------------------------------------------------------------------------
alias src='source ~/.bash_profile'
