#!/bin/zsh


# Allow VS Code (or others) to call a command during shell init
#-------------------------------------------------------------------------------
if [[ -n $ZSH_INIT_COMMAND ]]; then
    echo "Running: $ZSH_INIT_COMMAND"
    eval "$ZSH_INIT_COMMAND"
fi


# Key bindings
#-------------------------------------------------------------------------------
# clear screen on ctrl+L
clear-terminal() { tput reset; zle redisplay; }
zle -N clear-terminal
bindkey '^K' clear-terminal


# zsh options
#-------------------------------------------------------------------------------
# Treat the #, ~ and ^ characters as part of patterns for filename
# generation, etc.  (An initial unquoted `~' always produces named directory
# expansion.)
setopt  extended_glob
# When listing files that are possible completions, show the type of each file
# with a trailing identifying mark.
setopt  list_types
# Append a trailing / to all directory names resulting from filename
# generation (globbing).
setopt  mark_dirs
# This  option  both  imports new commands from the history file, and also
# causes your typed commands to be appended to the history file
setopt  share_history
# If a new command line being added to the history list duplicates an older one,
# the older command is removed from the list (even if it is not the previous event).
setopt  hist_ignore_all_dups


# History settings
#-------------------------------------------------------------------------------
HISTFILE=$HOME/.zsh_history
HISTFILESIZE=65536
HISTSIZE=4096
SAVEHIST=4096
REPORTTIME=60       # Report time statistics for progs that take more than a minute to run


# Modify coloring on ls command
#-------------------------------------------------------------------------------
export LSCOLORS=gxfxcxdxbxegedabagacad


# Auto completion using arrow keys, based on history
#-------------------------------------------------------------------------------
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward


# Tab completion
#-------------------------------------------------------------------------------
autoload -Uz compinit
compinit -C
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "$LS_COLORS"
zstyle -e ':completion:*:(ssh|scp|sshfs|ping|telnet|nc|rsync):*' hosts '
    reply=( ${=${${(M)${(f)"$(<~/.ssh/config)"}:#Host*}#Host }:#*\**} )'


# Source other files from the repo
#-------------------------------------------------------------------------------
source ~/.dotfiles/shell_setup/generic_shell_config


# zsh specific aliases
#-------------------------------------------------------------------------------
alias src='source ~/.zshrc'

# Source the promt
#-------------------------------------------------------------------------------
if [[ ! -n "$ZSHRUN" ]]; then
    source ~/.dotfiles/shell_setup/zsh_prompt > /dev/null 2>&1
fi
local -a precmd_functions
precmd_functions=( precmd_prompt )
