#!/bin/zsh

source ~/.dotfiles/aliases

# Source the prompt
#-------------------------------------------------------------------------------
if [[ ! -n "$ZSHRUN" ]]; then
    source ~/.dotfiles/shell_setup/zsh_prompt > /dev/null 2>&1
fi
local -a precmd_functions
precmd_functions=( precmd_prompt )

# Key bindings
#-------------------------------------------------------------------------------
# clear screen on ctrl+L
clear-terminal() { tput reset; zle redisplay; }
zle -N clear-terminal
bindkey '^L' clear-terminal
